# Build matrix
language: c
matrix:
  include:
    # OS X 10.11
    - os: osx
      osx_image: xcode7.3
      compiler: clang

    # OS X 10.12
    - os: osx
      osx_image: xcode8.3
      compiler: clang

  # OS X 10.13
    - os: osx
      osx_image: xcode9.4
      compiler: clang

# Build dependencies & diagnostics
before_install:
  - brew update
  - cmake --version || brew install cmake
  - brew install --force openssl
  - export PKG_CONFIG_PATH=/usr/local/opt/openssl/lib/pkgconfig:${PKG_CONFIG_PATH}

# Build library dependencies
install:
  - ./make-dependencies.sh

# Set pkg-config path, dynamic library path and binary path (since we prefix)
before_script:
  - export BUILD_PATH=$HOME/build/rawrtc/rawrtc-data-channel/build
  - export LD_LIBRARY_PATH=${BUILD_PATH}/prefix/lib:${LD_LIBRARY_PATH}
  - export PATH=${BUILD_PATH}/prefix/bin:${PATH}

# Build library
script:
  - cd build
  - >
    cmake
    -DCMAKE_INSTALL_PREFIX=${BUILD_PATH}/prefix
    -DCMAKE_C_FLAGS="-Werror -Wall -Wno-unused-function"
    .. && make install
